# Generated by Django 2.1.7 on 2019-02-12 19:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id')),
                ('name', models.CharField(db_index=True, max_length=127, verbose_name='Name')),
                ('p_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='P Code')),
                ('admin_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], verbose_name='Admin Level')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('local_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Local Name')),
                ('alternate_name_en1', models.CharField(blank=True, max_length=127, null=True, verbose_name='English Name')),
                ('alternate_name_en2', models.CharField(blank=True, max_length=127, null=True, verbose_name='English Name 2')),
                ('alternate_name_en3', models.CharField(blank=True, max_length=127, null=True, verbose_name='English Name 3')),
                ('alternate_name_fr1', models.CharField(blank=True, max_length=127, null=True, verbose_name='French Name')),
                ('alternate_name_fr2', models.CharField(blank=True, max_length=127, null=True, verbose_name='French Name 2')),
                ('alternate_name_fr3', models.CharField(blank=True, max_length=127, null=True, verbose_name='French Name 3')),
                ('alternate_name_es1', models.CharField(blank=True, max_length=127, null=True, verbose_name='Spanish Name')),
                ('alternate_name_es2', models.CharField(blank=True, max_length=127, null=True, verbose_name='Spanish Name 2')),
                ('alternate_name_es3', models.CharField(blank=True, max_length=127, null=True, verbose_name='Spanish Name 3')),
                ('alternate_name_ar1', models.CharField(blank=True, max_length=127, null=True, verbose_name='Arabic Name')),
                ('alternate_name_ar2', models.CharField(blank=True, max_length=127, null=True, verbose_name='Arabic Name 2')),
                ('alternate_name_ar3', models.CharField(blank=True, max_length=127, null=True, verbose_name='Arabic Name 3')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.Location', verbose_name='Parent')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.SubCategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'p_code')},
        ),
    ]
