# Generated by Django 2.1.7 on 2019-02-14 17:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id')),
                ('name', models.CharField(db_index=True, max_length=127, verbose_name='Name')),
                ('p_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='P Code')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('local_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Local Name')),
                ('local_name2', models.CharField(blank=True, max_length=127, null=True, verbose_name='Local Name 2')),
                ('local_name3', models.CharField(blank=True, max_length=127, null=True, verbose_name='Local Name 3')),
                ('alternate_name_en1', models.CharField(blank=True, max_length=127, null=True, verbose_name='English Name')),
                ('alternate_name_en2', models.CharField(blank=True, max_length=127, null=True, verbose_name='English Name 2')),
                ('alternate_name_en3', models.CharField(blank=True, max_length=127, null=True, verbose_name='English Name 3')),
                ('alternate_name_fr1', models.CharField(blank=True, max_length=127, null=True, verbose_name='French Name')),
                ('alternate_name_fr2', models.CharField(blank=True, max_length=127, null=True, verbose_name='French Name 2')),
                ('alternate_name_fr3', models.CharField(blank=True, max_length=127, null=True, verbose_name='French Name 3')),
                ('alternate_name_es1', models.CharField(blank=True, max_length=127, null=True, verbose_name='Spanish Name')),
                ('alternate_name_es2', models.CharField(blank=True, max_length=127, null=True, verbose_name='Spanish Name 2')),
                ('alternate_name_es3', models.CharField(blank=True, max_length=127, null=True, verbose_name='Spanish Name 3')),
                ('alternate_name_ar1', models.CharField(blank=True, max_length=127, null=True, verbose_name='Arabic Name')),
                ('alternate_name_ar2', models.CharField(blank=True, max_length=127, null=True, verbose_name='Arabic Name 2')),
                ('alternate_name_ar3', models.CharField(blank=True, max_length=127, null=True, verbose_name='Arabic Name 3')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry')),
                ('gender', models.CharField(choices=[('cod', 'COD'), ('global', 'Global')], max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Admin Boundaries',
            },
        ),
        migrations.CreateModel(
            name='BoundaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=15)),
                ('admin_level', models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], verbose_name='Admin Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=True, help_text='Default name for country and level')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adminboundary',
            name='boundary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundaries.BoundaryType'),
        ),
        migrations.AddField(
            model_name='adminboundary',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='adminboundary',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boundaries.AdminBoundary', verbose_name='Parent'),
        ),
    ]
