# Generated by Django 2.1.7 on 2019-02-26 21:11

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id')),
                ('name_en', models.CharField(blank=True, max_length=127, null=True, verbose_name='English Name')),
                ('name_fr', models.CharField(blank=True, max_length=127, null=True, verbose_name='French Name')),
                ('name_es', models.CharField(blank=True, max_length=127, null=True, verbose_name='Spanish Name')),
                ('name_ar', models.CharField(blank=True, max_length=127, null=True, verbose_name='Arabic Name')),
                ('alternate_names', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry')),
                ('gender', models.CharField(choices=[('cod', 'COD'), ('global', 'Global')], max_length=15)),
                ('name', models.CharField(db_index=True, max_length=127, verbose_name='Name')),
                ('p_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='P Code')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Admin Boundaries',
            },
        ),
        migrations.CreateModel(
            name='BoundaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id')),
                ('description', models.CharField(max_length=15)),
                ('admin_level', models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], verbose_name='Admin Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.Category', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id')),
                ('name', models.CharField(db_index=True, max_length=127, verbose_name='Name')),
                ('fullname', models.CharField(blank=True, db_index=True, max_length=127, null=True, verbose_name='Full Name')),
                ('alternate_name', models.CharField(blank=True, db_index=True, max_length=127, null=True, verbose_name='Alternate Name')),
                ('iso_code_2', models.CharField(max_length=2, unique=True, verbose_name='ISO code 2')),
                ('iso_code_3', models.CharField(max_length=3, unique=True, verbose_name='ISO code 3')),
                ('un_number', models.CharField(blank=True, max_length=3, null=True, verbose_name='UN Number')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antartica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id')),
                ('name_en', models.CharField(blank=True, max_length=127, null=True, verbose_name='English Name')),
                ('name_fr', models.CharField(blank=True, max_length=127, null=True, verbose_name='French Name')),
                ('name_es', models.CharField(blank=True, max_length=127, null=True, verbose_name='Spanish Name')),
                ('name_ar', models.CharField(blank=True, max_length=127, null=True, verbose_name='Arabic Name')),
                ('alternate_names', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=127, verbose_name='Name')),
                ('p_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='P Code')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='boundarytype',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AddField(
            model_name='boundarytype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.BoundaryType', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='boundary',
            name='boundary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BoundaryType'),
        ),
        migrations.AddField(
            model_name='boundary',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AddField(
            model_name='boundary',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Boundary', verbose_name='Parent'),
        ),
    ]
