# Generated by Django 2.2b1 on 2019-03-21 17:37

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='state',
            field=django_fsm.FSMField(choices=[('Pending Approval', 'Pending Approval'), ('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=50, verbose_name='Record State'),
        ),
        migrations.AlterField(
            model_name='boundarytype',
            name='state',
            field=django_fsm.FSMField(choices=[('Pending Approval', 'Pending Approval'), ('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=50, verbose_name='Record State'),
        ),
        migrations.AlterField(
            model_name='country',
            name='state',
            field=django_fsm.FSMField(choices=[('Pending Approval', 'Pending Approval'), ('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=50, verbose_name='Record State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=django_fsm.FSMField(choices=[('Pending Approval', 'Pending Approval'), ('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=50, verbose_name='Record State'),
        ),
        migrations.AlterField(
            model_name='uploadprocessor',
            name='state',
            field=django_fsm.FSMField(choices=[('preparing', 'preparing'), ('ready', 'ready'), ('queued', 'queued'), ('in progress', 'in progress'), ('canceled', 'canceled'), ('failed', 'failed'), ('succeeded', 'succeeded')], default='preparing', max_length=50, verbose_name='State'),
        ),
    ]
