# Generated by Django 2.1.7 on 2019-02-14 17:49

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID')),
                ('name', models.CharField(db_index=True, max_length=127, verbose_name='Name')),
                ('fullname', models.CharField(blank=True, db_index=True, max_length=127, null=True, verbose_name='Full Name')),
                ('alternate_name', models.CharField(blank=True, db_index=True, max_length=127, null=True, verbose_name='Alternate Name')),
                ('iso_code_2', models.CharField(max_length=2, unique=True, verbose_name='ISO code 2')),
                ('iso_code_3', models.CharField(max_length=3, unique=True, verbose_name='ISO code 3')),
                ('un_number', models.CharField(blank=True, max_length=3, null=True, verbose_name='UN Number')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antartica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
